server:
  port: 9090
spring:
  application:
    name: CONFIGSERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SarveshM369/learnspringbootmicroservices/blob/main/application.yaml
          clone-on-start: true    
